version: "3.8"

services:
  app:
    image: platziapp
    environment:
      MONGO_URL: "mongodb://db:27017/test"
    depends_on:
      - db
    ports:
      - "3000:3000" # host_port:conatiner_port
      # "3000" # docker-compose up -d --scale app=3; Al host le asignará puertos aleatorios
      # "9110-9120:3000" # docker-compose up -d --scale app=3; Al host le asignará puertos aleatorios
    resources:
        limits:
          memory: 100m
  db:
    image: mongo
