#FROM ubuntu:trusty
#CMD ["/bin/ping", "-c", "3", "localhost"]

FROM ubuntu:trusty
ENTRYPOINT [ "/bin/ping", "-c", "3"]
CMD ["localhost"]

#docker run -it [image_name] [linux command in container]  # run with command
#docker run -it [image_name] google.com ; google.com reeemplazará a localhost

